/* ============================================================================
   大阪生活 · Osaka Life —— 内容数据
   ----------------------------------------------------------------------------
   这个文件就是整站的「数据库」。本质是一个 JSON 对象，套了一层 window 变量，
   只是为了能【双击 index.html 直接打开】（不用起本地服务器）。

   ✅ 怎么改：照着下面任意一条复制，改字段即可。新增删除都在 items 里。
   ✅ 定时更新：scripts/update-content.mjs 会读写本文件（见 README）。

   字段说明：
     id        唯一编号（数字，别重复）
     module    所属模块：'food' | 'travel' | 'events' | 'social' | 'market'
     category  仅【美食】用：'chinese' | 'japanese' | 'thai' | 'korean'
     area      区域（用于「区域搜索」），见下方 AREAS
     emoji     没有真实图时显示的占位 emoji
     cover     封面图（可选）：'images/xxx.jpg' 或 https 链接；填了就显示真实图，不填用 emoji
     images    多图（可选）：['images/a.jpg','images/b.jpg']，详情页显示可点的小图廊
     title     标题
     author    作者：{ name, avatar(emoji) }   —— 对标小红书笔记作者
     likes / collects / comments   互动数（字符串，可带 w）
     tags      话题标签数组
     desc      正文/描述
     address   地址（填了才会在详情里显示 Google 地图；社交/二手可不填）
     price     人均（可选，美食用）
     hours     营业时间（可选）
     date      时间（同城活动/约饭用，可选）
     contact   联系方式（活动/交友/二手用，可选）
     source    溯源（爬虫写入用）：{ platform, url }
   ============================================================================ */
window.OSAKA_DATA = {
  updatedAt: "2026-06-03",

  // 模块（顶部导航，顺序即展示顺序）
  modules: [
    { key: "food",   label: "美食",     icon: "🍜" },
    { key: "travel", label: "日本旅游", icon: "🗼" },
    { key: "events", label: "同城约饭", icon: "🎉" },
    { key: "social", label: "交友搭子", icon: "👯" },
    { key: "market", label: "二手闲置", icon: "🛍️" },
  ],

  // 美食子分类
  foodCategories: [
    { key: "chinese",  label: "中餐", icon: "🥟" },
    { key: "japanese", label: "日料", icon: "🍣" },
    { key: "thai",     label: "泰餐", icon: "🍤" },
    { key: "korean",   label: "韩餐", icon: "🥘" },
  ],

  // 区域（区域搜索下拉，顺序即展示顺序）
  areas: [
    "难波/心斋桥",
    "梅田/大阪站",
    "天王寺/阿倍野",
    "新世界/通天阁",
    "鹤桥(韩国城)",
    "日本桥/黑门",
    "本町/堺筋本町",
    "京桥/大阪城",
    "美国村",
    "港区/天保山",
    "此花区(USJ)",
    "关西/其他",
  ],

  items: [
    /* ============================ 美食 · 中餐 ============================ */
    {
      id: 101, module: "food", category: "chinese", area: "难波/心斋桥", emoji: "🌶️",
      cover: "https://images.pexels.com/photos/30915727/pexels-photo-30915727.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      title: "难波这家四川火锅 麻辣够味｜在大阪吃到家乡的辣",
      author: { name: "关西吃货阿May", avatar: "🍙" },
      likes: "2.3w", collects: "9876", comments: "1203",
      tags: ["四川火锅", "麻辣", "解乡愁", "聚餐"],
      desc: "在大阪想吃地道麻辣火锅来这家就对了。牛油锅底是真的辣、真的香，毛肚鸭肠新鲜，还有藤椒和番茄锅可选。中文菜单+店员会说中文，约人聚餐很方便。人均 3500 円左右，记得早点去不然要排队。",
      address: "大阪市中央区难波 1丁目", price: "¥¥", hours: "17:00–24:00",
    },
    {
      id: 102, module: "food", category: "chinese", area: "梅田/大阪站", emoji: "🍜",
      cover: "https://images.pexels.com/photos/19252760/pexels-photo-19252760.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      title: "梅田西安刀削面｜肉夹馍+油泼面 北方胃的福音",
      author: { name: "浪速生活手帐", avatar: "🐼" },
      likes: "8654", collects: "5421", comments: "432",
      tags: ["刀削面", "肉夹馍", "西安", "北方菜"],
      desc: "梅田车站走路几分钟，油泼扯面和刀削面都很正，辣子香、面筋道，肉夹馍肥瘦相间。一个人吃也自在，价格实惠。留学生和上班族午饭好去处。",
      address: "大阪市北区角田町 梅田", price: "¥", hours: "11:00–22:00",
    },
    {
      id: 103, module: "food", category: "chinese", area: "难波/心斋桥", emoji: "🍲",
      cover: "https://images.pexels.com/photos/36054292/pexels-photo-36054292.png?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese hotpot restaurant",
      mapQuery: "海底捞火锅 心斎橋 大阪",
      title: "海底捞 大阪心斋桥店｜火锅+变脸+美甲 一条龙",
      author: { name: "大阪小晴", avatar: "🐰" },
      likes: "5.1w", collects: "2.6w", comments: "3120",
      tags: ["海底捞", "火锅", "川式", "服务好"],
      desc: "国内的海底捞开到大阪啦，川式锅底正、服务还是那个夸张的好：等位有零食、吃饭送围裙，还有变脸表演和美甲。番茄锅、麻辣锅、菌汤都能点，蘸料台随便调。想念国内火锅的来这家最解馋，人多建议先取号。",
      address: "大阪市中央区西心斎桥", price: "¥¥¥", hours: "11:00–翌2:00",
    },
    {
      id: 104, module: "food", category: "chinese", area: "日本桥/黑门", emoji: "🌶️",
      cover: "https://images.pexels.com/photos/34618075/pexels-photo-34618075.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "sichuan boiled fish chili",
      mapQuery: "麻辣江湖 難波 大阪",
      title: "麻辣江湖 难波本店｜正宗川味 圆桌包间适合聚餐",
      author: { name: "关西吃货阿May", avatar: "🍙" },
      likes: "1.7w", collects: "9210", comments: "880",
      tags: ["四川菜", "水煮鱼", "包间", "聚餐"],
      desc: "日本桥站走 5 分钟，主打正宗四川菜：水煮鱼、毛血旺、辣子鸡、夫妻肺片都很到位，辣得过瘾。有带圆桌的豪华包间，人多聚餐或宴请很合适。在大阪想吃硬核川菜可以冲。",
      address: "大阪市中央区日本桥", price: "¥¥", hours: "11:00–23:00",
    },
    {
      id: 105, module: "food", category: "chinese", area: "本町/堺筋本町", emoji: "🍜",
      cover: "https://images.pexels.com/photos/35285400/pexels-photo-35285400.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "lanzhou beef noodle soup",
      mapQuery: "功夫 蘭州ラーメン 大阪",
      title: "功夫兰州拉面 本町｜清汤牛肉面 西北那口踏实",
      author: { name: "浪速生活手帐", avatar: "🐼" },
      likes: "9876", collects: "5630", comments: "470",
      tags: ["兰州拉面", "牛肉面", "西北菜", "平价"],
      desc: "堺筋本町一带的兰州牛肉面，清汤够鲜、萝卜辣子香菜齐全，面可选二细/毛细/韭叶。再配一份手抓饭或凉拌牛肉绝了。在日本想喝一碗踏实的牛肉面来这家，价格也友好。",
      address: "大阪市中央区北久宝寺町", price: "¥", hours: "11:00–22:00",
    },
    {
      id: 106, module: "food", category: "chinese", area: "难波/心斋桥", emoji: "🥘",
      cover: "https://images.pexels.com/photos/6646090/pexels-photo-6646090.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "mapo tofu sichuan",
      mapQuery: "中華料理 森本 心斎橋 大阪",
      title: "心斋桥 森本｜招牌肥肠麻婆豆腐 一开门就满座",
      author: { name: "Yuki在大阪", avatar: "🌸" },
      likes: "2.4w", collects: "1.3w", comments: "1560",
      tags: ["麻婆豆腐", "肥肠", "心斋桥", "名店"],
      desc: "心斋桥的人气中华，开门就几乎满座。招牌「肥肠麻婆豆腐」在大阪很少见，麻辣浓香、肥肠处理得干净，配米饭一绝。位子不多，建议早点去或避开饭点。",
      address: "大阪市中央区东心斎桥", price: "¥¥", hours: "11:30–14:00 / 17:30–22:00",
    },
    {
      id: 107, module: "food", category: "chinese", area: "难波/心斋桥", emoji: "🥟",
      cover: "https://images.pexels.com/photos/19021565/pexels-photo-19021565.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "soup dumplings xiaolongbao",
      mapQuery: "上海食苑 心斎橋 大阪",
      title: "上海食苑 心斋桥｜现包小笼包 师傅从上海请来",
      author: { name: "关西吃货阿May", avatar: "🍙" },
      likes: "1.9w", collects: "1.1w", comments: "1020",
      tags: ["小笼包", "上海菜", "点心", "现包"],
      desc: "心斋桥的上海点心专门店，点心师傅从上海请来，小笼包现点现包，皮薄汤多、咬开爆汁。生煎、烧卖、上海菜饭也地道。想吃江浙沪那口的来这家。",
      address: "大阪市中央区心斎桥筋", price: "¥¥", hours: "11:00–22:00",
    },
    {
      id: 108, module: "food", category: "chinese", area: "难波/心斋桥", emoji: "🍖",
      cover: "https://images.pexels.com/photos/37924340/pexels-photo-37924340.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "grilled lamb skewers xinjiang",
      mapQuery: "刀郎餐厅 島之内 大阪",
      title: "刀郎餐厅｜新疆维吾尔菜 大盘鸡+烤串吃边疆味",
      author: { name: "美国村潮人", avatar: "🛹" },
      likes: "1.1w", collects: "6740", comments: "590",
      tags: ["新疆菜", "羊肉串", "大盘鸡", "拉条子"],
      desc: "岛之内的新疆/维吾尔料理，主打羊肉：烤羊肉串、手抓羊肉、大盘鸡配拉条子，分量豪爽。孜然香气十足，配馕和酸奶很对味。在大阪想吃边疆风味这家很难得。",
      address: "大阪市中央区島之内", price: "¥¥", hours: "17:00–24:00",
    },
    {
      id: 109, module: "food", category: "chinese", area: "难波/心斋桥", emoji: "🍚",
      cover: "https://images.pexels.com/photos/29160636/pexels-photo-29160636.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese fried rice wok",
      mapQuery: "恒源小吃 道頓堀 大阪",
      title: "恒源小吃 道顿堀｜深夜中华小吃 炒饭炒面砂锅都有",
      author: { name: "大阪小晴", avatar: "🐰" },
      likes: "8120", collects: "3450", comments: "402",
      tags: ["中华小吃", "深夜食堂", "炒饭", "平价"],
      desc: "道顿堀附近的中华小吃店，菜单像国内大排档：蛋炒饭、肉丝炒面、麻辣烫、各种砂锅，深夜也开。价格亲民、份量实在，逛完道顿堀来一碗热乎的很治愈，满满留学生食堂既视感。",
      address: "大阪市中央区道頓堀", price: "¥", hours: "11:00–翌3:00",
    },
    {
      id: 110, module: "food", category: "chinese", area: "梅田/大阪站", emoji: "🍲",
      cover: "https://images.pexels.com/photos/8178437/pexels-photo-8178437.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese clay pot stew",
      mapQuery: "圓石 北新地 大阪",
      title: "圆石本店 北新地｜45年老店 沙茶石锅是招牌",
      author: { name: "浪速生活手帐", avatar: "🐼" },
      likes: "6230", collects: "2980", comments: "330",
      tags: ["老字号", "石锅", "沙茶", "北新地"],
      desc: "北新地开了 45 年以上的老牌中华，招牌是用汉方药酒调味的石锅料理「沙茶」，香气独特、暖胃下饭。环境适合正式一点的聚餐宴请，是老大阪都知道的一家。",
      address: "大阪市北区曽根崎新地", price: "¥¥¥", hours: "17:00–23:00",
    },

    /* ============================ 美食 · 日料 ============================ */
    {
      id: 111, module: "food", category: "japanese", area: "难波/心斋桥", emoji: "🦀",
      cover: "https://images.pexels.com/photos/28559495/pexels-photo-28559495.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      title: "かに道楽 道顿堀本店｜大螃蟹招牌下吃蟹会席",
      author: { name: "Yuki在大阪", avatar: "🌸" },
      likes: "4.1w", collects: "1.8w", comments: "2098",
      tags: ["螃蟹料理", "道顿堀", "地标", "会席"],
      desc: "道顿堀那只会动的大螃蟹招牌就是它家，几乎是大阪打卡地标。蟹刺身、烤蟹脚、蟹火锅、蟹寿司一套吃下来很满足。想体验仪式感选会席套餐，预算有限可以只点单品。建议预约靠窗位。",
      address: "大阪市中央区道顿堀 1-6-18", price: "¥¥¥", hours: "11:00–22:00",
    },
    {
      id: 112, module: "food", category: "japanese", area: "难波/心斋桥", emoji: "🍜",
      cover: "https://images.pexels.com/photos/15085069/pexels-photo-15085069.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      title: "一兰拉面 道顿堀本馆｜24小时 一人食隔间豚骨",
      author: { name: "大阪小晴", avatar: "🐰" },
      likes: "6.7w", collects: "3.2w", comments: "3401",
      tags: ["豚骨拉面", "24小时", "一人食", "可定制"],
      desc: "深夜饿了随时能去，独立隔间一个人吃完全不尴尬。纸单上自己勾汤底浓淡、辣度、面硬度，加面按钮一按再来一份。本馆还有二楼河景座。第一次来选基础+秘制辣酱 0.5 倍很稳。",
      address: "大阪市中央区宗右卫门町 7-18", price: "¥¥", hours: "24小时",
    },
    {
      id: 113, module: "food", category: "japanese", area: "难波/心斋桥", emoji: "🍣",
      cover: "https://images.pexels.com/photos/11594188/pexels-photo-11594188.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      title: "大起水产 回转寿司｜平价新鲜 一盘100円起",
      author: { name: "关西吃货阿May", avatar: "🍙" },
      likes: "1.5w", collects: "8932", comments: "654",
      tags: ["回转寿司", "平价", "新鲜", "亲子"],
      desc: "本地人也常去的平价回转寿司，主打渔港直送，金枪鱼、鰤鱼、海胆都很新鲜，现点现做也很快。不踩雷、适合预算友好的一餐，带小孩或一个人都合适。",
      address: "大阪市中央区难波 千日前", price: "¥", hours: "11:00–22:00",
    },
    {
      id: 114, module: "food", category: "japanese", area: "难波/心斋桥", emoji: "🥘",
      cover: "https://images.pexels.com/photos/23614255/pexels-photo-23614255.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      title: "美津の 大阪烧｜米其林必比登 山药烧入口即化",
      author: { name: "浪速生活手帐", avatar: "🐼" },
      likes: "5.6w", collects: "2.7w", comments: "1890",
      tags: ["大阪烧", "米其林必比登", "山药烧", "老字号"],
      desc: "1945 年的大阪烧名店，常年米其林必比登推荐。招牌「山药烧」几乎全是山芋泥，蓬松流心和普通面糊完全不同。门口排队是日常，建议错峰。和章鱼烧并称大阪两大粉物代表。",
      address: "大阪市中央区道顿堀 1-4-15", price: "¥¥¥", hours: "11:00–22:00",
    },

    /* ============================ 美食 · 泰餐 ============================ */
    {
      id: 121, module: "food", category: "thai", area: "梅田/大阪站", emoji: "🍤",
      cover: "https://images.pexels.com/photos/20258248/pexels-photo-20258248.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      title: "梅田泰国菜 Mango Tree｜冬阴功+绿咖喱 正宗泰味",
      author: { name: "Yuki在大阪", avatar: "🌸" },
      likes: "7321", collects: "4210", comments: "388",
      tags: ["泰国菜", "冬阴功", "绿咖喱", "约会"],
      desc: "梅田高层的泰国餐厅，景观好适合约会。冬阴功酸辣到位、绿咖喱椰香浓，泰式炒河粉和芒果糯米饭也好吃。午市套餐性价比高。想吃辣记得跟店员说要原版辣度。",
      address: "大阪市北区 梅田", price: "¥¥", hours: "11:00–23:00",
    },
    {
      id: 122, module: "food", category: "thai", area: "美国村", emoji: "🥗",
      cover: "https://images.pexels.com/photos/34699471/pexels-photo-34699471.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      title: "美国村泰式小馆｜青木瓜沙拉够酸辣 街头风",
      author: { name: "美国村潮人", avatar: "🛹" },
      likes: "3120", collects: "1876", comments: "210",
      tags: ["泰式街头", "青木瓜沙拉", "打抛饭", "氛围"],
      desc: "藏在美国村小巷里的泰式小馆，价格亲民、分量足。青木瓜沙拉 Som Tam 够酸辣，打抛猪饭配煎蛋很下饭。装修有东南亚街头感，逛美国村累了进来歇脚正好。",
      address: "大阪市中央区西心斋桥 美国村", price: "¥", hours: "12:00–22:00",
    },

    /* ============================ 美食 · 韩餐 ============================ */
    {
      id: 131, module: "food", category: "korean", area: "鹤桥(韩国城)", emoji: "🥩",
      cover: "https://images.pexels.com/photos/18426528/pexels-photo-18426528.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      title: "鹤桥韩国城烤肉｜炭火和牛 烟火气拉满",
      author: { name: "大阪小晴", avatar: "🐰" },
      likes: "2.8w", collects: "1.4w", comments: "1560",
      tags: ["韩式烤肉", "鹤桥", "和牛", "韩国城"],
      desc: "鹤桥是大阪的韩国城，一出站就是浓浓的烤肉香。这家炭火烤和牛油花漂亮，配上泡菜和包饭一口一个满足。烟火气十足、价格比心斋桥实惠。整条街都是韩餐韩货，吃完还能逛市场。",
      address: "大阪市生野区鹤桥 2丁目", price: "¥¥", hours: "16:00–24:00",
    },
    {
      id: 132, module: "food", category: "korean", area: "鹤桥(韩国城)", emoji: "🍲",
      cover: "https://images.pexels.com/photos/35064872/pexels-photo-35064872.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      title: "鹤桥部队锅+芝士排骨｜两个人吃到扶墙",
      author: { name: "关西吃货阿May", avatar: "🍙" },
      likes: "1.9w", collects: "1.1w", comments: "920",
      tags: ["部队锅", "芝士排骨", "韩餐", "聚餐"],
      desc: "韩国城里的人气韩餐馆，部队锅料足汤辣、芝士排骨拉丝很爽。还有海鲜葱饼和韩式炸鸡。两个人点一锅+一份就很饱。想吃韩餐又不想只吃烤肉的来这家，选择多。",
      address: "大阪市生野区鹤桥", price: "¥¥", hours: "11:00–23:00",
    },

    /* ============================ 日本旅游 ============================ */
    {
      id: 201, module: "travel", area: "京桥/大阪城", emoji: "🏯",
      cover: "https://images.pexels.com/photos/30813051/pexels-photo-30813051.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      title: "大阪城公园｜天守阁登顶+护城河 一日漫步路线",
      author: { name: "Yuki在大阪", avatar: "🌸" },
      likes: "5.2w", collects: "3.6w", comments: "2210",
      tags: ["大阪城", "天守阁", "赏樱", "散步"],
      desc: "大阪必去地标。天守阁登顶俯瞰全城，护城河和西之丸庭园四季都好拍，春天樱花、秋天银杏。建议地铁森之宫站进，慢慢逛到京桥，半天到一天都合适。城内有历史展览，喜欢历史的别错过。",
      address: "大阪市中央区大阪城 1-1", hours: "公园全天 / 天守阁 9:00–17:00",
    },
    {
      id: 202, module: "travel", area: "难波/心斋桥", emoji: "🎐",
      cover: "https://images.pexels.com/photos/34728996/pexels-photo-34728996.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      title: "道顿堀｜固力果跑跑人+运河夜景 必拍清单",
      author: { name: "浪速生活手帐", avatar: "🐼" },
      likes: "8.9w", collects: "4.1w", comments: "3902",
      tags: ["道顿堀", "固力果", "夜景", "美食街"],
      desc: "大阪的心脏地带，霓虹招牌+运河夜景怎么拍都好看。固力果跑跑人广告牌是经典打卡点，傍晚到夜里最美。两岸全是美食：章鱼烧、大阪烧、拉面、螃蟹。可以坐道顿堀游船从水上看夜景。",
      address: "大阪市中央区道顿堀", hours: "全天",
    },
    {
      id: 203, module: "travel", area: "新世界/通天阁", emoji: "🗼",
      cover: "https://images.pexels.com/photos/15924866/pexels-photo-15924866.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      title: "新世界 & 通天阁｜昭和复古下町 串炸一条街",
      author: { name: "大阪小晴", avatar: "🐰" },
      likes: "3.7w", collects: "2.2w", comments: "1340",
      tags: ["通天阁", "新世界", "昭和复古", "串炸"],
      desc: "大阪最有下町烟火气的地方，通天阁脚下全是昭和复古招牌和串炸店。白天逛街、登塔看景，晚上吃串炸配啤酒最对味。和天王寺动物园、阿倍野 HARUKAS 离得近，可以串一条线。",
      address: "大阪市浪速区惠美须东 1丁目", hours: "通天阁 10:00–20:00",
    },
    {
      id: 204, module: "travel", area: "港区/天保山", emoji: "🐳",
      cover: "https://images.pexels.com/photos/27555660/pexels-photo-27555660.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      title: "海游馆｜世界最大级水族馆 鲸鲨太治愈",
      author: { name: "Yuki在大阪", avatar: "🌸" },
      likes: "4.4w", collects: "2.9w", comments: "1670",
      tags: ["海游馆", "水族馆", "鲸鲨", "亲子"],
      desc: "世界最大级水族馆之一，巨型水槽里的鲸鲨是镇馆之宝，水母区梦幻治愈。亲子和情侣都合适，旁边就是天保山大摩天轮和圣玛丽亚号游船，可以安排半天。建议网上买票免排队。",
      address: "大阪市港区海岸通 1-1-10", hours: "10:00–20:00",
    },
    {
      id: 205, module: "travel", area: "梅田/大阪站", emoji: "🌇",
      cover: "https://images.pexels.com/photos/19577642/pexels-photo-19577642.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      title: "梅田蓝天大厦 空中庭园｜大阪最美黄昏展望台",
      author: { name: "美国村潮人", avatar: "🛹" },
      likes: "3.1w", collects: "1.9w", comments: "1102",
      tags: ["梅田蓝天大厦", "空中庭园", "夜景", "黄昏"],
      desc: "梅田地标，顶层环形空中庭园 360° 看大阪。傍晚去先看落日再看万家灯火，性价比超高。冬天还有灯饰。从大阪站走过去有点绕，跟着指示牌走地下通道更快。",
      address: "大阪市北区大淀中 1-1-88", hours: "9:30–22:30",
    },
    {
      id: 206, module: "travel", area: "此花区(USJ)", emoji: "🎢",
      cover: "https://images.pexels.com/photos/3888315/pexels-photo-3888315.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      title: "日本环球影城 USJ｜任天堂世界+哈利波特 攻略",
      author: { name: "关西吃货阿May", avatar: "🍙" },
      likes: "12w", collects: "8.3w", comments: "6201",
      tags: ["USJ", "任天堂世界", "哈利波特", "快速通行"],
      desc: "关西头号主题乐园。超级任天堂世界要靠 App 抽整理券或买快速通行，热门项目排队很久。建议提前买门票+快速通行，早开园前到门口。哈利波特城堡和园区夜晚最出片。备好充电宝和舒适鞋。",
      address: "大阪市此花区桜岛 2-1-33", hours: "随季节调整，请查官网",
    },

    /* ============================ 同城约饭 / 活动 ============================ */
    {
      id: 301, module: "events", area: "难波/心斋桥", emoji: "🍲",
      cover: "https://images.pexels.com/photos/16143648/pexels-photo-16143648.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      title: "本周六晚 难波四川火锅局｜还差3-4人 AA",
      author: { name: "大阪小晴", avatar: "🐰" },
      likes: "326", collects: "88", comments: "142",
      tags: ["约饭", "火锅", "周末", "AA制"],
      desc: "周六 18:30 难波集合一起吃四川火锅，目前 4 人，想凑到 7-8 人热闹点。AA 人均预估 3500 円。在日留学生/上班族都欢迎，进群先报个坐标和爱好~ 评论区或私信扣 1。",
      address: "大阪市中央区难波 1丁目", date: "本周六 18:30", contact: "评论区扣1 / 私信",
    },
    {
      id: 302, module: "events", area: "京桥/大阪城", emoji: "🌸",
      cover: "https://images.pexels.com/photos/31588362/pexels-photo-31588362.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      title: "樱花季 大阪城赏樱野餐团｜带点零食饮料就行",
      author: { name: "Yuki在大阪", avatar: "🌸" },
      likes: "512", collects: "203", comments: "176",
      tags: ["赏樱", "野餐", "大阪城", "交友"],
      desc: "趁樱花季组个赏樱野餐，大阪城西之丸庭园集合，铺垫子晒太阳聊天拍照。自带零食饮料 share 着吃。新朋友超欢迎，社恐也别怕，氛围很松弛。下雨顺延，进群通知。",
      address: "大阪市中央区大阪城 西之丸庭园", date: "樱花季周末（视花期）", contact: "进群联系",
    },

    /* ============================ 交友 / 搭子 ============================ */
    {
      id: 401, module: "social", area: "关西/其他", emoji: "📚",
      cover: "https://images.pexels.com/photos/5409045/pexels-photo-5409045.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      title: "找日语学习搭子｜N2备考互相监督 线上线下都行",
      author: { name: "浪速生活手帐", avatar: "🐼" },
      likes: "289", collects: "156", comments: "98",
      tags: ["学习搭子", "日语", "N2", "互助"],
      desc: "12 月考 N2，想找搭子互相监督打卡，每周线上对一次答案，住关西的话偶尔图书馆自习。坐标大阪，水平 N3 左右，求同频不卷不躺的伙伴~",
      contact: "私信交换联系方式",
    },
    {
      id: 402, module: "social", area: "关西/其他", emoji: "🧳",
      cover: "https://images.pexels.com/photos/20704802/pexels-photo-20704802.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      title: "5月关西旅游搭子｜京都奈良和歌山 拼车拼住",
      author: { name: "美国村潮人", avatar: "🛹" },
      likes: "431", collects: "210", comments: "133",
      tags: ["旅游搭子", "京都", "奈良", "拼车"],
      desc: "5 月中想玩京都+奈良+和歌山，3-4 天，拼车拼住摊平成本。我负责做攻略和订住宿，求 2-3 个靠谱搭子，作息正常爱拍照的最好。有大致行程了，私信发你看。",
      contact: "私信 / 评论区留坐标",
    },

    /* ============================ 二手 / 闲置 ============================ */
    {
      id: 501, module: "market", area: "梅田/大阪站", emoji: "🪑",
      cover: "https://images.pexels.com/photos/34956532/pexels-photo-34956532.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      title: "搬家转让｜宜家书桌+人体工学椅 整套打包便宜出",
      author: { name: "关西吃货阿May", avatar: "🍙" },
      likes: "176", collects: "64", comments: "57",
      tags: ["二手", "搬家转让", "家具", "宜家"],
      desc: "下月回国，宜家书桌（八成新）+人体工学椅整套出，原价两万多円，现 6000 円打包。梅田自取，能帮忙搬到楼下。有需要的私信看实拍图，先到先得。",
      address: "大阪市北区 梅田（自取）", price: "¥6000", contact: "私信看图 / 自取",
    },
    {
      id: 502, module: "market", area: "天王寺/阿倍野", emoji: "🚲",
      cover: "https://images.pexels.com/photos/33262917/pexels-photo-33262917.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      title: "9成新通勤自行车转让｜带车筐车锁 天王寺自取",
      author: { name: "大阪小晴", avatar: "🐰" },
      likes: "203", collects: "71", comments: "44",
      tags: ["二手", "自行车", "通勤", "天王寺"],
      desc: "毕业离开大阪，通勤用的自行车转让，骑了不到一年九成新，带车筐和两把车锁，已上防盗登录可过户。8000 円，天王寺站附近自取，诚心要的小刀可以聊~",
      address: "大阪市天王寺区（自取）", price: "¥8000", contact: "私信约自取",
    },
    {
      id: 503, module: "food", category: "chinese", area: "美国村", emoji: "🥡",
      cover: "https://images.pexels.com/photos/36684497/pexels-photo-36684497.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.6749826,135.4758148",
      title: "餃子の王将",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐","gyoza"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese;gyoza）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/1619040549","name":"餃子の王将"},
    },
    {
      id: 504, module: "food", category: "chinese", area: "梅田/大阪站", emoji: "🥡",
      cover: "https://images.pexels.com/photos/7594074/pexels-photo-7594074.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.7291751,135.5008297",
      title: "加藤屋 大阪にぼ次郎",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/1638986498","name":"加藤屋 大阪にぼ次郎"},
    },
    {
      id: 505, module: "food", category: "chinese", area: "关西/其他", emoji: "🥡",
      cover: "https://images.pexels.com/photos/32188266/pexels-photo-32188266.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.6130978,135.490419",
      title: "広州",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/1715392874","name":"広州"},
    },
    {
      id: 506, module: "food", category: "chinese", area: "美国村", emoji: "🥡",
      cover: "https://images.pexels.com/photos/28235492/pexels-photo-28235492.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.6682892,135.4875947",
      title: "北京",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/1716037270","name":"北京"},
    },
    {
      id: 507, module: "food", category: "chinese", area: "关西/其他", emoji: "🥡",
      cover: "https://images.pexels.com/photos/8093885/pexels-photo-8093885.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.7312524,135.4302741",
      title: "大阪王將",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：japanese;chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/1737247288","name":"大阪王將"},
    },
    {
      id: 508, module: "food", category: "chinese", area: "梅田/大阪站", emoji: "🥡",
      cover: "https://images.pexels.com/photos/7492234/pexels-photo-7492234.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.7111461,135.5111195",
      title: "中華食堂十八番",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/1742835230","name":"中華食堂十八番"},
    },
    {
      id: 509, module: "food", category: "chinese", area: "梅田/大阪站", emoji: "🥡",
      cover: "https://images.pexels.com/photos/15690931/pexels-photo-15690931.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.711716,135.5035333",
      title: "豊崎飯店",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/1852587937","name":"豊崎飯店"},
    },
    {
      id: 510, module: "food", category: "chinese", area: "梅田/大阪站", emoji: "🥡",
      cover: "https://images.pexels.com/photos/34618081/pexels-photo-34618081.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.7174736,135.4796513",
      title: "大叛王將",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：japanese;chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/1996735560","name":"大叛王將"},
    },
    {
      id: 511, module: "food", category: "chinese", area: "梅田/大阪站", emoji: "🥡",
      cover: "https://images.pexels.com/photos/32860303/pexels-photo-32860303.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.7226839,135.4903404",
      title: "手作り餃子 橋郷館",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/1996735563","name":"手作り餃子 橋郷館"},
    },
    {
      id: 512, module: "food", category: "chinese", area: "梅田/大阪站", emoji: "🥡",
      cover: "https://images.pexels.com/photos/36680510/pexels-photo-36680510.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.7000189,135.5115222",
      title: "錦華園",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/2050781288","name":"錦華園"},
    },
    {
      id: 513, module: "food", category: "chinese", area: "梅田/大阪站", emoji: "🥡",
      cover: "https://images.pexels.com/photos/16211353/pexels-photo-16211353.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.6971846,135.5118096",
      title: "王将",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/2050962278","name":"王将"},
    },
    {
      id: 514, module: "food", category: "chinese", area: "梅田/大阪站", emoji: "🥡",
      cover: "https://images.pexels.com/photos/35421075/pexels-photo-35421075.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.6972052,135.5123557",
      title: "大龍ラーメン",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/2052484358","name":"大龍ラーメン"},
    },
    {
      id: 515, module: "food", category: "chinese", area: "梅田/大阪站", emoji: "🥡",
      cover: "https://images.pexels.com/photos/6390372/pexels-photo-6390372.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.6971452,135.5118084",
      title: "チャオチャオ餃子",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/2055586692","name":"チャオチャオ餃子"},
    },
    {
      id: 516, module: "food", category: "chinese", area: "梅田/大阪站", emoji: "🥡",
      cover: "https://images.pexels.com/photos/5088767/pexels-photo-5088767.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.6978831,135.5117688",
      title: "大陸風",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/2055586782","name":"大陸風"},
    },
    {
      id: 517, module: "food", category: "chinese", area: "京桥/大阪城", emoji: "🥡",
      cover: "https://images.pexels.com/photos/32149281/pexels-photo-32149281.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.6915408,135.5458631",
      title: "紅蘭",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/2142065387","name":"紅蘭"},
    },
    {
      id: 518, module: "food", category: "chinese", area: "京桥/大阪城", emoji: "🥡",
      cover: "https://images.pexels.com/photos/29168863/pexels-photo-29168863.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.6910395,135.5462369",
      title: "利河",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/2150488860","name":"利河"},
    },
    {
      id: 519, module: "food", category: "chinese", area: "本町/堺筋本町", emoji: "🥡",
      cover: "https://images.pexels.com/photos/32860326/pexels-photo-32860326.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.685064,135.508264",
      title: "一隆",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/2209597529","name":"一隆"},
    },
    {
      id: 520, module: "food", category: "chinese", area: "难波/心斋桥", emoji: "🥡",
      cover: "https://images.pexels.com/photos/31992493/pexels-photo-31992493.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.66535,135.502243",
      title: "饺子的王将",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐","gyoza"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese;gyoza）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/2276775322","name":"饺子的王将"},
    },
    {
      id: 521, module: "food", category: "chinese", area: "梅田/大阪站", emoji: "🥡",
      cover: "https://images.pexels.com/photos/8093524/pexels-photo-8093524.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.707541,135.511955",
      title: "大萊軒",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/2290087854","name":"大萊軒"},
    },
    {
      id: 522, module: "food", category: "chinese", area: "难波/心斋桥", emoji: "🥡",
      cover: "https://images.pexels.com/photos/7594049/pexels-photo-7594049.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.662479,135.499772",
      title: "中华料理大福",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/2294512459","name":"中华料理大福"},
    },
    {
      id: 523, module: "food", category: "chinese", area: "梅田/大阪站", emoji: "🥡",
      cover: "https://images.pexels.com/photos/7594077/pexels-photo-7594077.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.6980872,135.4810699",
      title: "マルイチ",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/2299235103","name":"マルイチ"},
    },
    {
      id: 524, module: "food", category: "chinese", area: "梅田/大阪站", emoji: "🥡",
      cover: "https://images.pexels.com/photos/7594052/pexels-photo-7594052.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.7076893,135.5114784",
      title: "精養軒",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/2300376378","name":"精養軒"},
    },
    {
      id: 525, module: "food", category: "chinese", area: "梅田/大阪站", emoji: "🥡",
      cover: "https://images.pexels.com/photos/7594063/pexels-photo-7594063.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.7072532,135.5025738",
      title: "龍華楼",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/2308965045","name":"龍華楼"},
    },
    {
      id: 526, module: "food", category: "chinese", area: "本町/堺筋本町", emoji: "🥡",
      cover: "https://images.pexels.com/photos/32149258/pexels-photo-32149258.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.688944,135.5064265",
      title: "香港飲茶 柏林苑",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/2310549533","name":"香港飲茶 柏林苑"},
    },
    {
      id: 527, module: "food", category: "chinese", area: "梅田/大阪站", emoji: "🥡",
      cover: "https://images.pexels.com/photos/8093968/pexels-photo-8093968.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.705563,135.511955",
      title: "新随園",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/2310930271","name":"新随園"},
    },
    {
      id: 528, module: "food", category: "chinese", area: "京桥/大阪城", emoji: "🥡",
      cover: "https://images.pexels.com/photos/7364006/pexels-photo-7364006.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.69776,135.546442",
      title: "新北京餐馆",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/2314243169","name":"新北京餐馆"},
    },
    {
      id: 529, module: "food", category: "chinese", area: "难波/心斋桥", emoji: "🥡",
      cover: "https://images.pexels.com/photos/15215399/pexels-photo-15215399.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.66634,135.499516",
      title: "中央軒",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/2315716827","name":"中央軒"},
    },
    {
      id: 530, module: "food", category: "chinese", area: "日本桥/黑门", emoji: "🥡",
      cover: "https://images.pexels.com/photos/5848595/pexels-photo-5848595.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.663369,135.504833",
      title: "けむり屋",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/2320394149","name":"けむり屋"},
    },
    {
      id: 531, module: "food", category: "chinese", area: "难波/心斋桥", emoji: "🥡",
      cover: "https://images.pexels.com/photos/7595212/pexels-photo-7595212.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.668845,135.505351",
      title: "刀削麺",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/2332967614","name":"刀削麺"},
    },
    {
      id: 532, module: "food", category: "chinese", area: "难波/心斋桥", emoji: "🥡",
      cover: "https://images.pexels.com/photos/30116650/pexels-photo-30116650.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.66732,135.505787",
      title: "香港楼",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/2333102153","name":"香港楼"},
    },
    {
      id: 533, module: "food", category: "chinese", area: "美国村", emoji: "🥡",
      cover: "https://images.pexels.com/photos/7594084/pexels-photo-7594084.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.671796,135.501055",
      title: "紅虎軒",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/2345156716","name":"紅虎軒"},
    },
    {
      id: 534, module: "food", category: "chinese", area: "梅田/大阪站", emoji: "🥡",
      cover: "https://images.pexels.com/photos/34618109/pexels-photo-34618109.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.697374,135.516578",
      title: "華食堂",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/2347053140","name":"華食堂"},
    },
    {
      id: 535, module: "food", category: "chinese", area: "京桥/大阪城", emoji: "🥡",
      cover: "https://images.pexels.com/photos/31328910/pexels-photo-31328910.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.696772,135.517655",
      title: "天府一品",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/2375846439","name":"天府一品"},
    },
    {
      id: 536, module: "food", category: "chinese", area: "梅田/大阪站", emoji: "🥡",
      cover: "https://images.pexels.com/photos/10201774/pexels-photo-10201774.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.7222613,135.4835023",
      title: "Standing酒場 ひとてま",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/2390381623","name":"Standing酒場 ひとてま"},
    },
    {
      id: 537, module: "food", category: "chinese", area: "难波/心斋桥", emoji: "🥡",
      cover: "https://images.pexels.com/photos/35673101/pexels-photo-35673101.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.671696,135.5022722",
      title: "たか鳥",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/2417533195","name":"たか鳥"},
    },
    {
      id: 538, module: "food", category: "chinese", area: "难波/心斋桥", emoji: "🥡",
      cover: "https://images.pexels.com/photos/31484080/pexels-photo-31484080.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.672044,135.503083",
      title: "三笠",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/2417543532","name":"三笠"},
    },
    {
      id: 539, module: "food", category: "chinese", area: "本町/堺筋本町", emoji: "🥡",
      cover: "https://images.pexels.com/photos/14747933/pexels-photo-14747933.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.686106,135.505816",
      title: "味宝楼",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/2450284400","name":"味宝楼"},
    },
    {
      id: 540, module: "food", category: "chinese", area: "本町/堺筋本町", emoji: "🥡",
      cover: "https://images.pexels.com/photos/16845596/pexels-photo-16845596.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.684491,135.5054509",
      title: "李白",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/2460155425","name":"李白"},
    },
    {
      id: 541, module: "food", category: "chinese", area: "梅田/大阪站", emoji: "🥡",
      cover: "https://images.pexels.com/photos/27039874/pexels-photo-27039874.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.7396524,135.5034526",
      title: "味悟空",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/2535952493","name":"味悟空"},
    },
    {
      id: 542, module: "food", category: "chinese", area: "梅田/大阪站", emoji: "🥡",
      cover: "https://images.pexels.com/photos/8256994/pexels-photo-8256994.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.6979208,135.5089247",
      title: "敲敲",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/2569658438","name":"敲敲"},
    },
    {
      id: 543, module: "food", category: "chinese", area: "本町/堺筋本町", emoji: "🥡",
      cover: "https://images.pexels.com/photos/28460877/pexels-photo-28460877.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.694092,135.5119446",
      title: "wanna manna",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐","taiwanese"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：taiwanese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/2608952728","name":"wanna manna"},
    },
    {
      id: 544, module: "food", category: "chinese", area: "日本桥/黑门", emoji: "🥡",
      cover: "https://images.pexels.com/photos/32860317/pexels-photo-32860317.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.6573315,135.505564",
      title: "玉華園",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/2610588635","name":"玉華園"},
    },
    {
      id: 545, module: "food", category: "chinese", area: "京桥/大阪城", emoji: "🥡",
      cover: "https://images.pexels.com/photos/36170479/pexels-photo-36170479.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.710765,135.5402824",
      title: "爆",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/2623366336","name":"爆"},
    },
    {
      id: 546, module: "food", category: "chinese", area: "京桥/大阪城", emoji: "🥡",
      cover: "https://images.pexels.com/photos/23702209/pexels-photo-23702209.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.6987509,135.5272929",
      title: "隨心亭",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/2702432467","name":"隨心亭"},
    },
    {
      id: 547, module: "food", category: "chinese", area: "京桥/大阪城", emoji: "🥡",
      cover: "https://images.pexels.com/photos/28399705/pexels-photo-28399705.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.712691,135.546931",
      title: "古城",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/2720175006","name":"古城"},
    },
    {
      id: 548, module: "food", category: "chinese", area: "关西/其他", emoji: "🥡",
      cover: "https://images.pexels.com/photos/16342613/pexels-photo-16342613.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.7131068,135.4526541",
      title: "金龍園（中華）",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/2875638324","name":"金龍園（中華）"},
    },
    {
      id: 549, module: "food", category: "chinese", area: "本町/堺筋本町", emoji: "🥡",
      cover: "https://images.pexels.com/photos/6646276/pexels-photo-6646276.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.6844368,135.5087759",
      title: "中華料理上海園",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/2936335005","name":"中華料理上海園"},
    },
    {
      id: 550, module: "food", category: "chinese", area: "京桥/大阪城", emoji: "🥡",
      cover: "https://images.pexels.com/photos/15897108/pexels-photo-15897108.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.709763,135.5264294",
      title: "中華×酒家 天頂",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/2936646704","name":"中華×酒家 天頂"},
    },
    {
      id: 551, module: "food", category: "chinese", area: "梅田/大阪站", emoji: "🥡",
      cover: "https://images.pexels.com/photos/8093525/pexels-photo-8093525.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.7055195,135.497851",
      title: "青冥",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/3150235530","name":"青冥"},
    },
    {
      id: 552, module: "food", category: "chinese", area: "关西/其他", emoji: "🥡",
      cover: "https://images.pexels.com/photos/8257029/pexels-photo-8257029.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.7316542,135.5593891",
      title: "大阪王将",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：japanese;chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/3150588615","name":"大阪王将"},
    },
    {
      id: 553, module: "food", category: "chinese", area: "关西/其他", emoji: "🥡",
      cover: "https://images.pexels.com/photos/32265588/pexels-photo-32265588.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.7278223,135.5705798",
      title: "大豊",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/3164237417","name":"大豊"},
    },
    {
      id: 554, module: "food", category: "chinese", area: "本町/堺筋本町", emoji: "🥡",
      cover: "https://images.pexels.com/photos/7595208/pexels-photo-7595208.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.6956035,135.5139143",
      title: "紅茶",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/3170034770","name":"紅茶"},
    },
    {
      id: 555, module: "food", category: "chinese", area: "本町/堺筋本町", emoji: "🥡",
      cover: "https://images.pexels.com/photos/8092495/pexels-photo-8092495.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.6958541,135.5140756",
      title: "福龍園",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/3170034773","name":"福龍園"},
    },
    {
      id: 556, module: "food", category: "chinese", area: "梅田/大阪站", emoji: "🥡",
      cover: "https://images.pexels.com/photos/36680491/pexels-photo-36680491.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.7074828,135.5036637",
      title: "PLUG",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/3176046161","name":"PLUG"},
    },
    {
      id: 557, module: "food", category: "chinese", area: "美国村", emoji: "🥡",
      cover: "https://images.pexels.com/photos/30169389/pexels-photo-30169389.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.666351,135.495032",
      title: "中国酒家 朝陽閣",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/3202661061","name":"中国酒家 朝陽閣"},
    },
    {
      id: 558, module: "food", category: "chinese", area: "京桥/大阪城", emoji: "🥡",
      cover: "https://images.pexels.com/photos/32610555/pexels-photo-32610555.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.7089209,135.531368",
      title: "格安王将 都島店",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/3257728061","name":"格安王将 都島店"},
    },
    {
      id: 559, module: "food", category: "chinese", area: "梅田/大阪站", emoji: "🥡",
      cover: "https://images.pexels.com/photos/27039900/pexels-photo-27039900.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.719742,135.523331",
      title: "丸源ラーメン",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/3496521796","name":"丸源ラーメン"},
    },
    {
      id: 560, module: "food", category: "chinese", area: "梅田/大阪站", emoji: "🥡",
      cover: "https://images.pexels.com/photos/28988078/pexels-photo-28988078.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.7009858,135.5003136",
      title: "珉珉",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/3668265924","name":"珉珉"},
    },
    {
      id: 561, module: "food", category: "chinese", area: "梅田/大阪站", emoji: "🥡",
      cover: "https://images.pexels.com/photos/5848539/pexels-photo-5848539.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.699067,135.4994688",
      title: "饺子王将",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐","gyoza"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese;gyoza）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/3678410016","name":"饺子王将"},
    },
    {
      id: 562, module: "food", category: "chinese", area: "鹤桥(韩国城)", emoji: "🥡",
      cover: "https://images.pexels.com/photos/7594079/pexels-photo-7594079.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.6537623,135.5490874",
      title: "万福",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/3751435544","name":"万福"},
    },
    {
      id: 563, module: "food", category: "chinese", area: "关西/其他", emoji: "🥡",
      cover: "https://images.pexels.com/photos/37417633/pexels-photo-37417633.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.7480756,135.4335277",
      title: "バーミヤン",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/3777492393","name":"バーミヤン"},
    },
    {
      id: 564, module: "food", category: "chinese", area: "梅田/大阪站", emoji: "🥡",
      cover: "https://images.pexels.com/photos/8093504/pexels-photo-8093504.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.7025486,135.5115696",
      title: "一品居",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/3891290586","name":"一品居"},
    },
    {
      id: 565, module: "food", category: "chinese", area: "梅田/大阪站", emoji: "🥡",
      cover: "https://images.pexels.com/photos/10201739/pexels-photo-10201739.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.7018478,135.510662",
      title: "真心",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/3891290599","name":"真心"},
    },
    {
      id: 566, module: "food", category: "chinese", area: "京桥/大阪城", emoji: "🥡",
      cover: "https://images.pexels.com/photos/14095308/pexels-photo-14095308.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.680458,135.54839",
      title: "味力亭",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/3897587459","name":"味力亭"},
    },
    {
      id: 567, module: "food", category: "chinese", area: "本町/堺筋本町", emoji: "🥡",
      cover: "https://images.pexels.com/photos/30842758/pexels-photo-30842758.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.6938202,135.511943",
      title: "餃子食堂 大阪亭",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/3954493854","name":"餃子食堂 大阪亭"},
    },
    {
      id: 568, module: "food", category: "chinese", area: "京桥/大阪城", emoji: "🥡",
      cover: "https://images.pexels.com/photos/20943966/pexels-photo-20943966.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.6922694,135.537261",
      title: "山藤飯店",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/3979028559","name":"山藤飯店"},
    },
    {
      id: 569, module: "food", category: "chinese", area: "本町/堺筋本町", emoji: "🥡",
      cover: "https://images.pexels.com/photos/8136892/pexels-photo-8136892.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.6849825,135.5177152",
      title: "味鮮閣",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/3996618527","name":"味鮮閣"},
    },
    {
      id: 570, module: "food", category: "chinese", area: "本町/堺筋本町", emoji: "🥡",
      cover: "https://images.pexels.com/photos/15215419/pexels-photo-15215419.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.6826392,135.5175481",
      title: "陳麻屋",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/3996618541","name":"陳麻屋"},
    },
    {
      id: 571, module: "food", category: "chinese", area: "鹤桥(韩国城)", emoji: "🥡",
      cover: "https://images.pexels.com/photos/6989840/pexels-photo-6989840.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.6647685,135.5438792",
      title: "成龍",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/3997582146","name":"成龍"},
    },
    {
      id: 572, module: "food", category: "chinese", area: "鹤桥(韩国城)", emoji: "🥡",
      cover: "https://images.pexels.com/photos/20943893/pexels-photo-20943893.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.6570307,135.5536719",
      title: "龍王苑",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/4144262107","name":"龍王苑"},
    },
    {
      id: 573, module: "food", category: "chinese", area: "梅田/大阪站", emoji: "🥡",
      cover: "https://images.pexels.com/photos/8092561/pexels-photo-8092561.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.7021271,135.499868",
      title: "かんじん堂",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：japanese;chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/4224513092","name":"かんじん堂"},
    },
    {
      id: 574, module: "food", category: "chinese", area: "京桥/大阪城", emoji: "🥡",
      cover: "https://images.pexels.com/photos/6646542/pexels-photo-6646542.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.6972444,135.5343337",
      title: "ぎょうざの満洲",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐","gyoza"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese;gyoza）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/4225126371","name":"ぎょうざの満洲"},
    },
    {
      id: 575, module: "food", category: "chinese", area: "关西/其他", emoji: "🥡",
      cover: "https://images.pexels.com/photos/7287722/pexels-photo-7287722.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.7245265,135.5610955",
      title: "麺屋 國丸。 旭軒",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐","ラーメン"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese;ラーメン）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/4232714921","name":"麺屋 國丸。 旭軒"},
    },
    {
      id: 576, module: "food", category: "chinese", area: "关西/其他", emoji: "🥡",
      cover: "https://images.pexels.com/photos/30987857/pexels-photo-30987857.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.5950551,135.5101973",
      title: "餃子王",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/4240843509","name":"餃子王"},
    },
    {
      id: 577, module: "food", category: "chinese", area: "鹤桥(韩国城)", emoji: "🥡",
      cover: "https://images.pexels.com/photos/5848603/pexels-photo-5848603.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.6617349,135.5621482",
      title: "中華食堂 山形屋",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/4362869555","name":"中華食堂 山形屋"},
    },
    {
      id: 578, module: "food", category: "chinese", area: "日本桥/黑门", emoji: "🥡",
      cover: "https://images.pexels.com/photos/7595203/pexels-photo-7595203.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.6623812,135.5037252",
      title: "一芳亭",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐","friture","chicken"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese;friture;chicken）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/4374292391","name":"一芳亭"},
    },
    {
      id: 579, module: "food", category: "chinese", area: "鹤桥(韩国城)", emoji: "🥡",
      cover: "https://images.pexels.com/photos/20522409/pexels-photo-20522409.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.6656828,135.5427161",
      title: "中国小皿料理 彩七",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/4429017614","name":"中国小皿料理 彩七"},
    },
    {
      id: 580, module: "food", category: "chinese", area: "鹤桥(韩国城)", emoji: "🥡",
      cover: "https://images.pexels.com/photos/37674222/pexels-photo-37674222.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.6616933,135.5496786",
      title: "快楽園",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/4453491006","name":"快楽園"},
    },
    {
      id: 581, module: "food", category: "chinese", area: "梅田/大阪站", emoji: "🥡",
      cover: "https://images.pexels.com/photos/24405865/pexels-photo-24405865.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.6981822,135.511508",
      title: "おばちゃんとこ（奥）",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/4553192556","name":"おばちゃんとこ（奥）"},
    },
    {
      id: 582, module: "food", category: "chinese", area: "本町/堺筋本町", emoji: "🥡",
      cover: "https://images.pexels.com/photos/6989872/pexels-photo-6989872.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      imgQuery: "chinese restaurant food",
      mapQuery: "34.6828428,135.5115875",
      title: "珉龍 本町橋店",
      author: { name: "地图收录·待完善", avatar: "🗺️" },
      likes: "0", collects: "0", comments: "0",
      tags: ["中餐"],
      desc: "来自 OpenStreetMap 的中餐收录（菜系：chinese）。招牌菜、点评和实拍图待补充——欢迎完善。",
      source: {"platform":"osm","id":"node/4626115628","name":"珉龍 本町橋店"},
    },
  ],
};
